const courses=[
    {
        id: 1,
        title: 'React Native for mobile app',
        img: require("../assets/img/newrelease1.jpg"),
        path: require("../assets/img/path1.png"),
        numCourses: 15,
        author: 'Hai Pham',
        level: 'Advance',
        released: 'May 6, 2020',
        duration: '30h',
        star: 3.5,
        num:34,
        pathName: "ReactNative"
    },
    {
        id: 2,
        title: 'Tim hieu React',
        img: require("../assets/img/newrelease2.jpg"),
        path: require("../assets/img/path2.jpg"),
        numCourses: 30,
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 7, 2020',
        duration: '14h 30',
        star: 3,
        num:3200,
        pathName: "ReactNative"
    },
    {
        id: 3,
        title: 'C Sharp Introduction',
        img: require("../assets/img/newrelease3.jpg"),
        path: require("../assets/img/path3.png"),
        numCourses: 10,
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'May 7, 2020',
        duration: '12m',
        star: 2,
        num:4600,
        pathName: "ReactNative"
    },
    {
        id: 4,
        title: 'Js for Beginner',
        img: require("../assets/img/newrelease4.jpg"),
        path: require("../assets/img/path4.png"),
        numCourses: 8,
        author: 'Pham Nguyen Dang Khoa',
        level: 'Beginner',
        released: 'June 7, 2019',
        duration: '14h 30',
        star: 1,
        num:450,
        pathName: "ReactNative"
    },
    {
        id: 5,
        title: 'IOS',
        img: require("../assets/img/newrelease5.jpg"),
        path: require("../assets/img/path4.png"),
        numCourses: 9,
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'July 7, 2018',
        duration: '14m',
        star: 4.5,
        num:760,
        pathName: "ReactNative"
    },
    {
        id: 4,
        title: 'Js for Beginner',
        img: require("../assets/img/newrelease4.jpg"),
        path: require("../assets/img/path4.png"),
        numCourses: 8,
        author: 'Pham Nguyen Dang Khoa',
        level: 'Beginner',
        released: 'June 7, 2019',
        duration: '14h 30',
        star: 1,
        num:450,
        pathName: "ReactNative"
    },
    {
        id: 6,
        title: 'Java for Developer',
        img: require("../assets/img/newrelease3.jpg"),
        path: require("../assets/img/path1.png"),
        numCourses: 9,
        author: 'Huy Nguyen',
        level: 'Beginner',
        released: 'July 7, 2018',
        duration: '14m',
        star: 4.5,
        num:760,
        pathName: "ReactNative"
    },
];

export default courses;